### ISSUE TITLE
Facing encoding issue while converting CSV to PDF

### ISSUE THREAD

**Issue by rudSarkar** [TECH-SAVVY-GUY/csv2pdf#1]
## Sample CSV
```
Order Item Id,Order Type,Order Flag,Daraz Id,Seller SKU,Daraz SKU,Created at,Updated at,Order Number,Invoice Required,Customer Name,Customer Email,National Registration Number,Shipping Name,Shipping Address,Shipping Address2,Shipping Address3,Shipping Address4,Shipping Address5,Shipping Phone Number,Shipping Phone Number2,Shipping City,Shipping Postcode,Shipping Country,Shipping Region,Billing Name,Billing Address,Billing Address2,Billing Address3,Billing Address4,Billing Address5,Billing Phone Number,Billing Phone Number2,Billing City,Billing Postcode,Billing Country,Payment Method,Paid Price,Unit Price,Shipping Fee,Wallet Credits,Item Name,Variation,CD Shipping Provider,Shipping Provider,Shipment Type Name,Shipping Provider Type,CD Tracking Code,Tracking Code,Tracking URL,Shipping Provider (first mile),Tracking Code (first mile),Tracking URL (first mile),Promised shipping time,Premium,Status,Cancel / Return Initiator,Reason,Reason Detail,Editor,Bundle ID,Bundle Discount,Refund Amount
```

## Used default code

```
from csv2pdf import convert
convert("order.list.export 2022-05-09.csv", "test-des-csv.pdf")
```

## Stack Trace

```python
$ python3
Python 3.9.12 (main, Mar 26 2022, 15:51:15)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from csv2pdf import convert
>>> convert("order.list.export 2022-05-09.csv", "test-des-csv.pdf")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fpdf/fpdf.py", line 3412, in normalize_text
    return txt.encode(self.core_fonts_encoding).decode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufeff' in position 0: ordinal not in range(256)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/csv2pdf.py", line 71, in convert
    PDF.multi_cell(col_width, line_height, cell, align=align, border=1,
  File "/usr/local/lib/python3.9/site-packages/fpdf/fpdf.py", line 274, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fpdf/fpdf.py", line 2870, in multi_cell
    txt = self.normalize_text(txt)
  File "/usr/local/lib/python3.9/site-packages/fpdf/fpdf.py", line 3414, in normalize_text
    raise FPDFUnicodeEncodingException(
fpdf.errors.FPDFUnicodeEncodingException: Character "﻿" at index 0 in text is outside the range of characters supported by the font used: "courierB". Please consider using a font that supports UTF-8 encoding.
>>> convert("order.list.export 2022-05-09.csv", "test-des-csv.pdf")..encode('iso-8859-1')
KeyboardInterrupt
>>> convert("order.list.export 2022-05-09.csv", "test-des-csv.pdf").encode('iso-8859-1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fpdf/fpdf.py", line 3412, in normalize_text
    return txt.encode(self.core_fonts_encoding).decode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufeff' in position 0: ordinal not in range(256)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/csv2pdf.py", line 71, in convert
    PDF.multi_cell(col_width, line_height, cell, align=align, border=1,
  File "/usr/local/lib/python3.9/site-packages/fpdf/fpdf.py", line 274, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fpdf/fpdf.py", line 2870, in multi_cell
    txt = self.normalize_text(txt)
  File "/usr/local/lib/python3.9/site-packages/fpdf/fpdf.py", line 3414, in normalize_text
    raise FPDFUnicodeEncodingException(
fpdf.errors.FPDFUnicodeEncodingException: Character "﻿" at index 0 in text is outside the range of characters supported by the font used: "courierB". Please consider using a font that supports UTF-8 encoding.
```

This issue is caused while it's trying to use [fpdf](https://pypi.org/project/fpdf/) functions.

**Comment by TECH-SAVVY-GUY** [comment]
Do you mind sharing the original PDF, as it seems there's a problem with some of the data which can't be properly encoded.

**Comment by tech-savvy-guy** [comment]
Do you mind sharing the original PDF, as it seems there's a problem with some of the data which can't be properly encoded?

**Comment by rudSarkar** [comment]
Finally, I find out that the issue with the CSV data I provided for convert, This application will doesn't work if there is no data available in columns. Closing this issue.
